import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/prisma";

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const feedback = await db.feedback.findUnique({
      where: { id },
      include: { project: true },
    });

    if (!feedback) {
      return NextResponse.json(
        { message: "Feedback not found" },
        { status: 404 }
      );
    }

    if (!feedback.spec) {
      return NextResponse.json(
        { message: "No spec available for this feedback" },
        { status: 400 }
      );
    }

    const spec = feedback.spec as any;
    const implementationText = generateImplementationText(feedback, spec);

    return NextResponse.json({
      text: implementationText,
      feedback: {
        id: feedback.id,
        type: feedback.type,
        text: feedback.text,
        project: {
          name: feedback.project.name,
          githubRepo: feedback.project.githubRepo,
        },
      },
    });
  } catch (error) {
    console.error("Error getting implementation:", error);
    return NextResponse.json(
      { message: "Failed to get implementation" },
      { status: 500 }
    );
  }
}

function generateImplementationText(
  feedback: any,
  spec: any
): string {
  const lines = [
    `## ${feedback.type === "bug" ? "Bug Fix" : "Feature Implementation"}`,
    ``,
    `**Feedback:** ${feedback.text}`,
    ``,
    `---`,
    ``,
    `**User Story**${spec.userStory ? ":" : ""}`,
    spec.userStory || "",
    ``,
    `**Acceptance Criteria:**`,
    ...(spec.acceptanceCriteria || []).map((crit: string) => `- [ ] ${crit}`),
    ``,
  ];

  if (spec.technicalNotes) {
    lines.push(`**Technical Notes:**`);
    lines.push(spec.technicalNotes);
    lines.push(``);
  }

  if (spec.assumptions && spec.assumptions.length > 0) {
    lines.push(`**Assumptions:**`);
    lines.push(...spec.assumptions.map((a: string) => `- ${a}`));
    lines.push(``);
  }

  if (spec.risks && spec.risks.length > 0) {
    lines.push(`**Risks to Consider:**`);
    lines.push(...spec.risks.map((r: string) => `- ${r}`));
    lines.push(``);
  }

  if (feedback.project.githubRepo) {
    lines.push(`**Repository:** ${feedback.project.githubRepo}`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(``);
  lines.push(`**Instructions:**`);
  lines.push(`1. Review the user story and acceptance criteria`);
  lines.push(`2. Implement the feature/fix following the AC`);
  lines.push(`3. Add appropriate tests`);
  lines.push(`4. Create a PR with clear description linking to this feedback`);
  lines.push(``);
  lines.push(`*Generated by PM Analyzer from customer feedback.*`);

  return lines.join("\n");
}
